config/routes.rb
Rails.application.routes.draw do
  root to: 'skills#edit'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users,except: [:index]
  resources :categories
  resources :skills,except: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :skills, dependent: :destroy
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :name, presence: true
  validates :level, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 8 },
                    format: { with: /\A(?=.*\d)(?=.*[a-zA-Z])\w{8,}\z/ },on: :create
               
  validates :introduce,length: { in: 50..200 }
  has_many :skills, dependent: :destroy
  before_validation { email.downcase! }
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required

    private

    def login_required
      redirect_to new_session_path unless current_user
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


  def new
     @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    if @category.save
      redirect_to category_path(@category.id)
    else
      render :new
    end
  end

    private

    def category_params
      params.require(:category).permit(:name )
    end


    def set_category
      @category = Category.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :login_required
  before_action :set_skill, only: [:new,:edit,:destroy]

  def new
    @user = current_user
    @skill = Skill.new
    @category_id = params[:category_id]
    @category = Category.find(params[:category_id])

  end

 def create
   @skill = current_user.skills.build(skill_params)
   @category_id = @skill.category_id
   if @skill.save
      flash[:success] = "#{@skill.category.name}に#{@skill.name}を習得レベル#{@skill.level}で追加しました！"
      redirect_to edit_skill_path(@skill)
    else

      redirect_to new_skill_path(category_id: @category_id)
    end
   end


  def edit
    @user = current_user
    if @user.skills.empty?
      frontend_category = Category.create(name: "フロントエンド")
      backend_category = Category.create(name: "バックエンド")
      infra_category = Category.create(name: "インフラ")
  
      frontend_skill = Skill.create(name: "サンプルスキル1", level: 0, category: frontend_category)
      backend_skill = Skill.create(name: "サンプルスキル2", level: 0, category: backend_category)
      infra_skill = Skill.create(name: "サンプルスキル3", level: 0, category: infra_category)
  
      @user.skills << frontend_skill
      @user.skills << backend_skill
      @user.skills << infra_skill
  
      @user_skills = @user.skills.includes(:category)
    else
      @user_skills = @user.skills.includes(:category)
    end
    @categories = @user_skills.map(&:category).uniq
    @frontend = @user_skills.where(category: frontend_category)
    @backend = @user_skills.where(category: backend_category)
    @infra = @user_skills.where(category: infra_category)
  end
  


  def update
    @categories = Category.all
    @skill = Skill.find(params[:id]) if params[:id]
    if @skill.update(update_params)
      flash[:success] = "#{@skill.name}の習得レベルを保存しました！"
      redirect_to edit_skill_path
    else
      flash[:danger] = "習得レベル保存に失敗しました"
      render :edit
    end
  end

  def destroy
   @skill = Skill.find(params[:id])
   @skill.destroy
   redirect_to edit_skill_path
   flash[:success] = "#{@skill.name}を削除しました"
  end

  private

    def skill_params
      params.require(:skill).permit(:name, :level,:category_id)
    end

    def set_skill
      @skills = current_user.skills
    end

    def update_params
      params.require(:skill).permit(:level)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required,only: [:show, :edit,:update]
  before_action :set_user, only: [:show, :edit, :update]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      flash.now[:danger] = 'ユーザーの作成に失敗しました'
      render :new
    end
  end

  def show
    @user = current_user
    @user_skills = @user.skills.includes(:category)
    @categories = @user_skills.map { |skill| skill.category }.uniq

    frontend_category_id = @categories.select { |category| category.name == "フロントエンド" }.pluck(:id)
    august_period = Time.new(2023, 8, 1)..Time.new(2023, 8, 31).end_of_day
    september_period = Time.new(2023, 9, 1)..Time.new(2023, 9, 30).end_of_day
    october_period = Time.new(2023, 10, 1)..Time.new(2023, 10, 31).end_of_day

    august_total = @user_skills.where(created_at: august_period,category_id: frontend_category_id).sum(:level)
    september_total = @user_skills.where(created_at: september_period ,category_id: frontend_category_id).sum(:level)
    october_total = @user_skills.where(created_at: october_period ,category_id: frontend_category_id).sum(:level)
    @frontend_data = [august_total, september_total, october_total]


    backend_category_id = @categories.select { |category| category.name == "バックエンド" }.pluck(:id)
    august_total = @user_skills.where(created_at: august_period,category_id: backend_category_id).sum(:level)
    september_total = @user_skills.where(created_at: september_period ,category_id: backend_category_id).sum(:level)
    october_total = @user_skills.where(created_at: october_period ,category_id: backend_category_id).sum(:level)
    @backend_data = [august_total, september_total, october_total]

    infra_category_id = @categories.select { |category| category.name == "バックエンド" }.pluck(:id)
    august_total = @user_skills.where(created_at: august_period,category_id: infra_category_id).sum(:level)
    september_total = @user_skills.where(created_at: september_period ,category_id: infra_category_id).sum(:level)
    october_total = @user_skills.where(created_at: october_period ,category_id: infra_category_id).sum(:level)
    @infra_data = [august_total, september_total, october_total]

  
  end

  

  def edit
    
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      @errors = @user.errors.full_messages
      flash.now[:danger] = '自己紹介の作成に失敗しました'
      render :edit
    end
  end 

  


    private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation,:image,:image_cache,:introduce)
    end


    def set_user
      @user = User.find(params[:id])
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper


def flash_class_for(flash_type)
  case flash_type.to_sym
  when :success
    "success"
  when :error, :alert
    "danger"
  when :notice
    "info"
  else
    "info"
  end
end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProfileApp</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>
  </head>

  <body>
    <header>
      <div class ="logo">
        <% if logged_in? %>
          <%= link_to "My profile", user_path(current_user),class: "logo-font" %>
        <% else %>
          <%= link_to "My profile", new_session_path, class: "logo-font" %>
        <% end %>
      </div>
      <% if logged_in? %>
       <%= button_to "ログアウト", session_path(current_user), method: :delete, class: "header-button" %>
      <% else %>
       <%= button_to "ログイン", new_session_path, method: :get, class: "header-button" %>
      <% end %>
　  </header>
　　<%= render 'skills/frash' %>
　　<main>
　　  <%= yield %>
　　</main>
    <footer>
      user name's profile site
    </footer>
  </body>
</html>

app/views/skills/_frash.html.erb
<% if logged_in? %>
  <% flash.each do |key, value| %>
    <div id="modal-overlay" class="overlay">
      <div class="center-alert">
        <div class ="value-area">
          <%= value %>
        </div>
        <% if key == 'success' %>
          <div class="button-area">
            <%= button_to "編集ページに戻る",edit_skill_path,method: :get,class: "button_back" %>
          </div>
        <% elsif key == 'danger' %>
          <div class="button-area">
　　　　    <%= button_to "戻る", edit_skill_path, method: :get,class: "button_back" %>
　　　　  </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/skills/edit.html.erb
<div class="skill-container">
  <% @categories.each do |category| %>
    <div class="skill-category <%= 'overflow-scroll' if category.skills.count >= 4 %>">
      <div class="skill-card">
        <div class="thead">
          <div class="category-name">
            <div class="name"><%= category.name %></div>
          </div>
  　　　  　　<div class="button-container">
   　　　   　　 <%= link_to "スキルを追加する", new_skill_path(category_id: category.id), method: :get, class: "skill-button",id: "skill_new" %>
  　　　　　　</div>
　　　  </div>
        <table class="skill-table">
          <tbody>
            <tr>
              <th class="header2">習得スキル</th>
              <th class="header2">習得レベル</th>
            </tr>
            <% category.skills.each_with_index do |skill, index| %>
              <tr>
                <td><%= skill.name %></td>
                <%= form_with model: skill, url: skill_path(skill), method: :patch, local: true do |f| %>
                  <td><%= f.select :level, (1..100).to_a, selected: skill.level, class: "custom-select-box skill-select-box-#{index}" %></td>
                  <td><%= button_to "習得レベルを保存する", skill_path(skill), method: :patch, class: "update-button skill-update-button-#{index}", id: "modal-open-update" %></td>
                <% end %>
                <td><%= button_to "スキルを削除する", skill_path(skill), method: :delete, class: "delete-button", id: "modal-open-delete" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</div>

app/views/skills/new.html.erb
<div class ="skill-new-head">
    <h1><%= @category.name %>にスキルを追加</h1>
</div>

<% if @skill.errors.any? %>
  <div id="error_explanation">
    <h2><%= @skill.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @skill.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<div class ="skill-new-body">
  <%= form_with(model: @skill, local: true) do |f| %>
    <div class="name-area">
      <%= f.label :スキル名 %>
      <%= f.text_field :name, class: "custom-input" %>
    </div>
    <div class="lebel-area">
      <%= f.label :習得レベル %>
      <%= f.select :level, (1..100).to_a, {}, { class: "custom-input custom-select" } %>
      <p>1~100の間で選択してください</p>
    </div>
    <%= f.hidden_field :category_id, value: "#{@category_id}" %>
    <div class="new-button-area">
      <%= f.submit "追加する", class: "new-button",id: "modal-open-create" %>
    </div>
  <% end %>
</div>

app/views/users/_flash.html.erb
<% flash.each do |key, value| %>
    <div class ="flash-area">
      <%= content_tag(:div, value, class: "#{key}") %>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user,url: user_path(@user), local: true,class: "center",method: :patch) do |f| %>
    <div class ="user-inner">
      <div class = "text-area">
        <%= f.label :自己紹介文 %><br>
        <%= f.text_area :introduce, class: "text-area-input", size: "65x5" %>
        <p>50文字以上、２００文字未満で入力してください</p>
      </div>


      <div class="image-area">
        <%= f.label :"アバター画像",class:"image-area-label" %><br>
        <div class ="custom-file-area">
          <%= f.label :image, class: "custom-file-label" do %>
          <span>画像ファイルを添付する</span>
        </div>
        <%= f.file_field :image, class: "custom-file-input" %>
        <% end %>
      </div>
      <div class ="actions">
       <%= f.submit "自己紹介を確定する",class:"user-edit-button" %>
      </div>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1 class ="login-title">自己紹介を編集する</h1>

<%= render partial: "form" %>

app/views/users/new.html.erb
<%= render partial: "flash" %>
<h1 class ="user-new-title">新規登録</h1>
<%= form_with(model: @user, local: true,class: "new-user-center") do |f| %>    
    <div class = "user-inner">
      <div class ="user-text-area">
        <div class = "filed">
          <%= f.label :メールアドレス %>
          <%= f.email_field :email, class: "input-underline",id: 'session_email' %>
      </div>
      <div class = "filed">
        <p> <%= f.label :パスワード %></p>
        <p> <%= f.password_field :password, class: "input-underline",id: 'session_password' %></p>
      </div>
    </div>
    <div class ="actions">
      <%= f.submit "登録する",class:"submit-button" %>
    </div>
    <%= f.hidden_field :name, value: "gest" %>
    <%= f.hidden_field :introduce, value: "サンプル" * 13 %>
  </div>
<% end %>

app/views/users/show.html.erb
  <div class = "show-all">
    <div class ="show">
    <div class ="image">
　    <p>
        <% if @user.image.present? %>
  　　      <%= image_tag @user.image.url,class: "rounded-circle", size: "360x360" %>
　      <% else %>
          <%= image_tag "gray.jpg",class: "rounded-circle", size: "360x360" %>
　      <% end %>
      </p>
    </div>

    <div class="profile">
      <h1>自己紹介</h1>
      <div class="user-info">
        <p><%= @user.introduce %></p>
        <td><%= button_to "自己紹介を編集する", edit_user_path(@user),method: :get,class: "edit-button" %></td>
      </div>
    </div>

    <div class = "skill">
      <div class = "skill-body">
        <div class = "skill-head">
          <h2>スキルチャート</h2>
　      </div>
　      <td><%= button_to "スキルを編集する", edit_skill_path(@user),method: :get,class: "edit-skill-button" %></td>
      </div>
    </div>
  </div>
  </div>


  <div class="chart-container">
    <canvas id="barChart"></canvas>
    <script>
    document.addEventListener("DOMContentLoaded", function () {
      let barCtx = document.getElementById("barChart");


      let frontendData = <%= @frontend_data.to_json.html_safe %>;
      let backendData = <%= @backend_data.to_json.html_safe %>;
      let infraData = <%= @infra_data.to_json.html_safe %>;

      let months = ['先々月', '先月', '今月'];
      console.log(infraData);
      console.log(backendData);
      console.log(frontendData)

      let barConfig = {
        type: 'bar',
        data: {
          labels: months,
          datasets: [{
            label: 'フロントエンド',
            data: frontendData,
        　   backgroundColor: 'rgba(244, 180, 196, 0.9)'
          }, {
            label: 'バックエンド',
            data: backendData,
            backgroundColor: 'rgba(244, 212, 172, 0.9)'
          }, {
            label: 'インフラ',
            data: infraData,frontendData,
            backgroundColor: 'rgba(251, 228, 180, 0.9)'
          }],
        },
        options: {
          scales: {
            y: {
              display: true,
              beginAtZero: true,
              suggestedMin: 0,
              suggestedMax: 100,
              stepSize: 20
            },
          },
        },
      };

      let barChart = new Chart(barCtx, barConfig);
    });
  </script>
  </div>